name: Deploy to EC2 staging server

on:
  push:
    branches: [staging]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on staging server
        if: contains(github.ref, 'staging')
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST_DEPLOY }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script_stop: true
          script: |
            set +e
            sudo kill -9 $(sudo lsof -t -i:8000) || true
            git clone git@github.com:Basak-SWM/wasak.git ~/app/wasak || true
            cd ~/app/wasak

            git branch staging || true
            git checkout staging
            git pull origin staging

            source ~/app/venvs/wasak/bin/activate
            cat ~/app/.secrets/wasak/.env > ./.env
            pip3 install -r ./requirements.txt

            nohup uvicorn main:app --port=8000 --host=0.0.0.0 > ../log/wasak.log 2>&1 &
