name: Deploy to EC2 as Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Set up Docker Buildx
        uses: docker/build-push-action@v4.1.1

      - name: Login to Dockerhub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Proxy Build And Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wasak

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, label-wasak]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker run
        run: |
          docker stop wasak && docker rm wasak && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/wasak:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/wasak:latest
          docker run -d -p 8000:8000 --name wasak ${{ secrets.DOCKERHUB_USERNAME }}/wasak:latest
