name: Deploy to EC2 as Docker

on:
  push:
    branches: [staging]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on staging server
        if: contains(github.ref, 'staging')
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST_DEPLOY }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script_stop: true
          script: |
            sudo kill -9 $(sudo lsof -t -i:8000)
            rm -rf ~/app/wasak
            git clone git@github.com:Basak-SWM/wasak.git ~/app/wasak
            cat ~/app/.secrets/wasak/.env > .env
            source ~/app/venvs/wasak/bin/activate
            pip3 install -r ~/app/wasak/requirements.txt
            uvicorn main:app --port 8000 &
